wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.13
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714637165.647568
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.6.13
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.0001
alpha:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 6
